Fixes a GNU compile time error
The error was due to gust_fac being declared as an array and used as
a scalar:

/global/cscratch1/sd/bsingh/delete/tmp/gnu_compile/E3SM/components/cam
/src/physics/cam/clubb_intr.F90:1253:30:

    real(r8) :: gust_fac(pcols)
                              1
Error: Argument 'gust_fac' of statement function at (1) must be scalar
/global/cscratch1/sd/bsingh/delete/tmp/gnu_compile/E3SM/components/cam
/src/physics/cam/clubb_intr.F90:1248:20:

    real(r8) :: ugust  ! function: gustiness as a function of
    convective rainfall
                    1
Error: Incompatible ranks 0 and 1 in assignment at (1)
/global/cscratch1/sd/bsingh/acme_scratch/cori-knl/SMS_Ln1.ne4_ne4.
FC5AV1C-L.cori-knl_gnu.gnu_tst_del/Tools/Makefile:934: recipe for
target 'clubb_intr.o' failed
gmake: *** [clubb_intr.o] Error 1

[BFB] - Bit-For-Bit
[NML] - Namelist Changing

See confluence for a more detailed description about these tags.