Add missing err initialization
This merge adds a missing err initialization to
li_setup_vertical_grid.  Without this fix and using gnu
compilers under linux, the err had a garbage value that triggered
MALI to quit with a generic error:

ERROR: An error has occurred in landice_init_block.
CRITICAL ERROR: An error has occurred in li_core_init. Aborting...